### ISSUE TITLE
403 Seite

### ISSUE THREAD

**Issue by zonky2** [OMOSde/contao-om-fastaccess#3]
leider kann man eine vorhandene 403-Seite von Contao nicht als Weiterleitungsseite angeben, da diese nicht "routable" ist :(

Man könnte die Pflichtangabe der Weiterleitung entfernen und wenn diese nicht gesetzt ist ein 403 bei fehlgeschlagener Prüfung erzeugen

```
// Send error 403.
$message = 'Zugriff nicht gestattet';
throw new AccessDeniedException($message);
```

**Comment by OMOSde** [comment]
Wird eine so erzeugte Exception von Contao abgefangen und dann auf eine eventuell vorhandene 403 geleitet?

**Comment by zonky2** [comment]
> Wird eine so erzeugte Exception von Contao abgefangen und dann auf eine eventuell vorhandene 403 geleitet?

Ja...

den Text sieht man (bei mir) aktuell nur im Debugmodus - die Anzeige im Content habe ich noch nicht hin bekommen ... sofern das überhaupt geht
siehe u.A. https://www.e-spin.de/files/e-spin/metamodels/vortrag/2023/Vortrag-Contao-Konferenz-2023.pdf Seite 23

**Comment by OMOSde** [comment]
Changed in 57faa17352fdb8337980cd7c86307ad72d701368
